# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3'

volumes:
  mysql_data:
      driver: local

services:
  createyourhumanity_angular-app:
    image: createyourhumanity_angular
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@https://registry.heartfull-mind.space/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@https://registry.heartfull-mind.space/config
      - SPRING_DATA_MONGODB_URI=mongodb://createyourhumanity_angular-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=createyourhumanity_angular
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://keycloak.createyourevent.org/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=9f608490-949a-4d83-95b0-f77c64f374bc
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  createyourhumanity_angular-mongodb:
    image: mongo:4.4.12
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ~/volumes/jhipster/createyourhumanity_angular/mongodb/:/data/db/

